global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'url-shortener-metrics'
    static_configs:
      - targets: ['url-shortener:8080']
        labels:
          service: 'url-shortener-metrics'
